config/routes.rb
PsReporting::Application.routes.draw do
  resources :architects

  resources :customers do
    resources :sows do
      resources :tasks
    end
  end

  get "home/index"

  match 'reports/engagements' => 'reports#engagements'

  root :to => 'home#index'

end

app/models/architect.rb
class Architect < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :name, :uniqueness => true, :presence => true
  has_many :sows, :dependent => :destroy
end

app/models/sow.rb
class Sow < ActiveRecord::Base
  belongs_to :customer
  has_many :tasks

  def percent_complete
    tasks.complete.sum{|t| t.duration.to_f} / tasks.sum {|t| t.duration.to_f} * 100
  end

  def dollars_worked
    percent_complete * self.price / 100
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :sow
  belongs_to :architect
  scope :complete, :conditions => {:complete => true}
  scope :incomplete, :conditions => {:complete => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/architects_controller.rb
class ArchitectsController < ApplicationController
  # GET /architects
  # GET /architects.json
  def index
    @architects = Architect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @architects }
    end
  end

  # GET /architects/1
  # GET /architects/1.json
  def show
    @architect = Architect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @architect }
    end
  end

  # GET /architects/new
  # GET /architects/new.json
  def new
    @architect = Architect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @architect }
    end
  end

  # GET /architects/1/edit
  def edit
    @architect = Architect.find(params[:id])
  end

  # POST /architects
  # POST /architects.json
  def create
    @architect = Architect.new(params[:architect])

    respond_to do |format|
      if @architect.save
        format.html { redirect_to @architect, notice: 'Architect was successfully created.' }
        format.json { render json: @architect, status: :created, location: @architect }
      else
        format.html { render action: "new" }
        format.json { render json: @architect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /architects/1
  # PUT /architects/1.json
  def update
    @architect = Architect.find(params[:id])

    respond_to do |format|
      if @architect.update_attributes(params[:architect])
        format.html { redirect_to @architect, notice: 'Architect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @architect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /architects/1
  # DELETE /architects/1.json
  def destroy
    @architect = Architect.find(params[:id])
    @architect.destroy

    respond_to do |format|
      format.html { redirect_to architects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def engagements
    @sows = Sow.find(:all)
    @total_dollars_worked = 0
    @total_dollars = 0
    @sows.each do |s|
      @total_dollars_worked += s.dollars_worked
      @total_dollars += s.price
    end
  end

end

app/controllers/sows_controller.rb
class SowsController < ApplicationController
  def create
    @customer = Customer.find(params[:customer_id])
    @sow = @customer.sows.create(params[:sow])
    redirect_to customer_path(@customer)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @sow = @customer.sows.find(params[:id])
    @sow.destroy
    redirect_to customer_path(@customer)
  end

  def show
    @sow = Sow.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @sow = Sow.find(params[:sow_id])
    @tasks = Task.find(:sow_id => @sow.id)
  end

  def create
    @sow = Sow.find(params[:sow_id])
    @task = @sow.tasks.create(params[:task])
    redirect_to customer_sow_path(params[:customer_id],@sow)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def destroy
    @sow = Sow.find(params[:sow_id])
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to customer_sow_path(params[:customer_id],@sow)
  end

  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to customer_sow_path(@task.sow.customer.id, @task.sow), notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/architects_helper.rb
module ArchitectsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sows_helper.rb
module SowsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/architects/_form.html.erb
<%= form_for(@architect) do |f| %>
  <% if @architect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@architect.errors.count, "error") %> prohibited this architect from being saved:</h2>

      <ul>
      <% @architect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/architects/edit.html.erb
<h1>Editing architect</h1>

<%= render 'form' %>

<%= link_to 'Show', @architect %> |
<%= link_to 'Back', architects_path %>

app/views/architects/index.html.erb
<h1>Listing architects</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @architects.each do |architect| %>
  <tr>
    <td><%= architect.name %></td>
    <td><%= link_to 'Show', architect %></td>
    <td><%= link_to 'Edit', edit_architect_path(architect) %></td>
    <td><%= link_to 'Destroy', architect, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Architect', new_architect_path %>

app/views/architects/new.html.erb
<h1>New architect</h1>

<%= render 'form' %>

<%= link_to 'Back', architects_path %>

app/views/architects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @architect.name %>
</p>


<%= link_to 'Edit', edit_architect_path(@architect) %> |
<%= link_to 'Back', architects_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table border="1">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= link_to 'Add/View/Alter SOWs', customer %></td>
    <td><%= link_to 'Change Name', edit_customer_path(customer) %></td>
    <td><%= link_to 'Delete', customer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>
<h2>SOWs</h2>
<table border="1">
  <% @customer.sows.each do |sow| %>
  <tr>
    <td><%= sow.id %></td>
    <td><%= link_to sow.category, customer_sow_path(sow.customer, sow) %></td>
    <td><%= sow.price %></td>
    <td><%= link_to 'Edit', [sow.customer, sow], :method => :edit%></td>
    <td><%= link_to 'Delete', [sow.customer, sow],
               :confirm => 'Are you sure?',
               :method => :delete %></td>
  </tr>
  <% end %>
</table>

<h2>Add an sow:</h2>
<%= render "sows/form" %>
<br/>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/home/index.html.erb
<h1>PS Home</h1>
<ol>
  <li><a href="/architects">Architects</a></li>
  <li><a href="/customers">Customers</a></li>
</ol>

app/views/reports/engagements.html.erb
<h1>Engagements Summary</h1>

<table border="1">
  <th>ID</th>
  <th>Architect(s)</th>
  <th>Customer</th>
  <th>Engagement Type</th>
  <th>Percent Complete</th>
  <th>Dollars Worked</th>
  <th>Total Price</th>
<% @sows.each do |sow| %>
  <tr>
    <td><%= sow.id %></td>
    <td><%= sow.tasks.collect(&:architect).flatten.collect(&:name).uniq.join(", ") %></td>
    <td><%= sow.customer.name %></td>
    <td><%= sow.category %></td>
    <td><%= sow.percent_complete %></td>
    <td><%= number_to_currency(sow.dollars_worked,:unit => "$") %></td>
    <td><%= number_to_currency(sow.price,:unit => "$") %></td>
  </tr>
<% end %>
  <tr>
    <td><h3>Totals:</h3></td>
    <td colspan="4">
    <td><%= number_to_currency(@total_dollars_worked,:unit => "$") %></td>
    <td><%= number_to_currency(@total_dollars,:unit => "$") %></td>
  </tr>
</table>

app/views/sows/_form.html.erb
<%= form_for([@customer, @customer.sows.build]) do |f| %>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label 'Documents Accepted' %>
    <%= f.check_box :docsaccepted %>
  </div>
  <div class="field">
    <%= f.label 'Revenue Recognized' %>
    <%= f.check_box :revrecd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sows/_sow.html.erb
<table border="1">
  <% @customer.sows.each do |sow| %>
  <tr><td><%= sow.category %></td><td><%= sow.price %></td></tr>
  <% end %>
</table>

app/views/sows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<h2>SOW for <%= @sow.customer.name %></h2>
<table border="1">
  <th>Category</th>
  <th>Price</th>
  <tr>
    <td><%= @sow.category %></td>
    <td><%= @sow.price %></td>
  </tr>
</table>

<h2>Tasks</h2>
<table border="1">
  <th>Description</th>
  <th>Duration</th>
  <th>Architect</th>
  <th>Complete</th>
  <% @sow.tasks.each do |task| %>
  <tr>
    <td><%= task.description %></td>
    <td><%= task.duration %></td>
    <td><%= task.architect.try(:name) %></td>
    <td><%= task.complete %></td>
    <td><%= link_to "Edit", edit_customer_sow_task_path(task.sow.customer, task.sow, task) %></td>
    <td><%= link_to 'Delete', [task.sow.customer, task.sow, task],
               :confirm => 'Are you sure?',
               :method => :delete %></td>
  </tr>
  <% end %>
</table>

<h2>Add a task:</h2>
<%= form_for([@sow.customer, @sow, @sow.tasks.build]) do |f| %>
  <div class="field">
    <%= f.label :description%><br />
    <%= f.text_field :description%>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :architect %><br />
    <%= f.select :architect_id, Architect.all.collect {|a| [a.name, a.id] }, { :include_blank => true }  %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select(:startdate, :start_year => 2012)  %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.date_select(:enddate)  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for([@task.sow.customer, @task.sow, @task]) do |f| %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task </h1>

<%= form_for([@task.sow.customer, @task.sow, @task]) do |f| %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :architect %><br />
    <%= f.select :architect_id, Architect.all.collect {|a| [a.name, a.id] }, { :include_blank => true }  %>
  </div>
  <div class="field">
    <%= f.label :complete %>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.date_select :enddate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', customer_sow_task_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Duration</th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= task.description %></td>
    <td><%= task.duration %></td>
  </tr>
<% end %>
</table>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>
<h2>SOWs</h2>
<table border="1">
  <% @customer.sows.each do |sow| %>
  <tr>
    <td><%= sow.category %></td>
    <td><%= link_to 'Add Tasks', customer_sow_path(sow.customer, sow) %></td>
    <td><%= sow.price %></td>
    <td><a target="_blank" href="<%= sow.link %>">Link to SOW in Dropbox</td>
    <td><%= link_to 'Edit', [sow.customer, sow], :method => :edit%></td>
    <td><%= link_to 'Delete', [sow.customer, sow],
               :confirm => 'Are you sure?',
               :method => :delete %></td>
  </tr>
  <% end %>
</table>

<h2>Add an SOW:</h2>
<%= render "sows/form" %>
<br/>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>